### ISSUE TITLE
Is there a way to set "permanently" after adjusting the temperature?

### ISSUE THREAD

**Issue by betabob** [derekprior/homebridge-schluter-thermostat#15]
I setup an automation to turn my thermostat down whenever no one is at home, and another to turn it back up when we arrive. However, this doesn't work so well for extended absences, as whenever the temperature is reset it changes the thermostat's "mode" to go back to "return to schedule" vs. "permanently". And as far as I can tell there is no way to remove scheduling entirely from the thermostat. So, is there a way to set "permanently" any time a temperature adjustment is made?

**Comment by betabob** [comment]
I did some googling around for the Schluter APIs and found that there is a variable called RegulationMode which does exactly what I want. And I also see that in the code that it is hardcoded to be set to "2"...I need it to be set to "3". It would be great if somebody can make a small update so that the Mode can be a plugin configuration setting. I may try and do this myself at some point, though my coding skills are quite dated and this is something that would take a knowledgable developer literally a few minutes to implement.

**Comment by winterborn** [comment]
Hey, I've got a quick fix for this, I'll PR it in.

**Comment by derekprior** [comment]
fixed by #16
