### ISSUE TITLE
Implement thermostat regulation modes and comfort end time handling

### ISSUE THREAD

**Issue by winterborn** [derekprior/homebridge-schluter-thermostat#18]
As per comments on issue [16](https://github.com/derekprior/homebridge-schluter-thermostat/pull/16):

_So, I just installed the latest version...thanks. However, I think there might be a problem. I updated my config and added "regulationMode": 3 so that any changes would be permanent. However, when I try to change the temperature from the Home app, though it does change the mode to permanent it doesn't seem to change the temperature. @winterborn can you take a look at this?_

I have created a fix for this:

https://github.com/derekprior/homebridge-schluter-thermostat/pull/17

Ready to merge.

**Comment by derekprior** [comment]
Thanks so much @winterborn 

FYI, if you put `fixes #<issue number>` in your commit or PR, then when that commit or PR is merged the issue will auto-close.
