### ISSUE TITLE
Handle exceptions in requests to Schluter API

### ISSUE THREAD

**Issue by derekprior** [derekprior/homebridge-schluter-thermostat#4]

**Comment by winterborn** [comment]
I have this ready [here](https://github.com/winterborn/homebridge-schluter-thermostat/commit/3978bfa3bf6be60dc52fcae7f7c0cf272bccf9ef) and need to raise a PR, but have based this off changes I previously PR'd [here](https://github.com/derekprior/homebridge-schluter-thermostat/pull/17) so this may need to be merged in first before I can raise another.
